version: '3.2'
volumes:
  kong-db:
    driver: local
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: CRUD
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped
  crud:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - environment_kong-net
      - postgres
    environment:
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/CRUD
      ISSUER_URI: http://iam:8080
      SPRING_PROFILES_ACTIVE: prod
networks:
  environment_kong-net:
    driver: overlay
    external: true
  postgres:
    driver: bridge