spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: CRUD
  datasource:
    url: jdbc:h2:mem:myDb;INIT=create schema if not exists CRUD;MODE=PostgreSQL
    driver-class-name: org.h2.Driver